{{- $module := index .Values.kubeStateMetrics -}}
{{- $module_name := "kube-state-metrics" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      serviceAccountName: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
      containers:
        - name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
          image: {{ $module.image.repository }}:{{ $module.image.tag }}
          imagePullPolicy: {{ $module.image.pullPolicy }}
          args:
            - --metric-labels-allowlist=pods=[app.kubernetes.io/component],deployments=[app.kubernetes.io/component]
            - >-
              --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
          resources:
            {{- $module.resources | toYaml | nindent 12 }}          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
          - containerPort: 8080
            name: http-metrics
          - containerPort: 8081
            name: telemetry
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  labels:
    app: prometheus
    job: kube-state-metrics
spec:
  jobLabel: job
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  namespaceSelector: 
    matchNames: [{{ .Values.namespace | quote }}]
  endpoints:
    - port: http-metrics
