{{- $module := index .Values.prometheus -}}
{{- $module_name := "prometheus" -}}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  image: {{ $module.image.repository }}:{{ $module.image.tag }}
  imagePullPolicy: {{ $module.image.pullPolicy }} 
  scrapeInterval: 15s
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  additionalScrapeConfigs: 
    name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
    key: additionalConfigs
  resources:
    {{- $module.resources | toYaml | nindent 4 }}
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
spec:
  selector:
    prometheus: {{ include "kube-metrics.fullname" . }}-prometheus
  ports:
    - port: 9090
      targetPort: 9090
