{{- $module := index .Values.prometheus -}}
{{- $module_name := "prometheus" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
type: Opaque
stringData:
  additionalConfigs: |
    {{- $module.additionalConfigs | toString| nindent 4 }}