{{- $module := .Values.monitoring.prometheus -}}
{{- $module_name := "prometheus" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-metrics.fullname" . }}-{{ $module_name }}
  namespace:  {{ .Release.Namespace }}
type: Opaque
stringData:
  additionalConfigs: |
    {{- $module.additionalConfigs | toString| nindent 4 }}